//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokOtomasyonProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.KullaniciRolleri = new HashSet<KullaniciRolleri>();
            this.Sepet = new HashSet<Sepet>();
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int ID { get; set; }
        [Display(Name="Kullanýcý Adý")]
        [Required(ErrorMessage = "Kullanýcý alaný boþ geçilemez")]
        public string KullaniciAdi { get; set; }
        [Display(Name = "Þifre")]
        [Required(ErrorMessage = "Þifre alaný boþ geçilemez")]
        public string Sifre { get; set; }
        [Display(Name = "Adý Soyadý")]
        [Required(ErrorMessage = "Adý Soyadý alaný boþ geçilemez")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = "Telefon alaný boþ geçilemez")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Adres alaný boþ geçilemez")]
        public string Adres { get; set; }
        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "E-mail alaný boþ geçilemez")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Tarih alaný boþ geçilemez")]
        public System.DateTime Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRolleri> KullaniciRolleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
